// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for TraceEvent.
const (
	COPY   TraceEvent = "COPY"
	CREATE TraceEvent = "CREATE"
	DELETE TraceEvent = "DELETE"
)

// Content A product's content contains the path and the filehash
type Content struct {
	Hash string `json:"hash"`
	Path string `json:"path"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// Input The input product used to derive a product from.
type Input struct {
	Hash        string `json:"hash"`
	ProductName string `json:"product_name"`
}

// Product A product is either a file itself, or a collection of files.
type Product struct {
	Contents *[]Content `json:"contents,omitempty"`
	Hash     string     `json:"hash"`
	Inputs   *[]Input   `json:"inputs,omitempty"`
	Name     string     `json:"name"`
	Size     int        `json:"size"`
}

// Signature The trace signature can be used to verify a products integrity.
//
// The signature is created using an asymetric, public-key encryption system.
// The bytes being signed corespond to the trace's product dictionary, in lower-case,
// compact JSON format (i.e. without whitespaces or linebreaks) and encoded in utf-8.
type Signature struct {
	Algorithm string `json:"algorithm"`
	PublicKey string `json:"public_key"`
	Signature string `json:"signature"`
}

// Trace A trace describes a specific event for a product at a specific origin.
type Trace struct {
	Event         TraceEvent `json:"event"`
	HashAlgorithm string     `json:"hash_algorithm"`
	Origin        string     `json:"origin"`
	Product       Product    `json:"product"`
	Signature     Signature  `json:"signature"`
	Timestamp     time.Time  `json:"timestamp"`
}

// TraceEvent A trace event describes how the trace comes into life.
//
// CREATE: A new product is generated.
// COPY: A product is copied from to a new location.
// DELETE: A product is removed from for a given reason.
type TraceEvent string

// TraceRegistration The results of a trace registration.
type TraceRegistration struct {
	Message string `json:"message"`
	Success bool   `json:"success"`
}

// TraceValidation The results of a trace validation
type TraceValidation struct {
	Message string `json:"message"`
	Success bool   `json:"success"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Loc  []ValidationError_Loc_Item `json:"loc"`
	Msg  string                     `json:"msg"`
	Type string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// PutTracesV1JSONBody defines parameters for PutTracesV1.
type PutTracesV1JSONBody = []Trace

// ValidateProductParams defines parameters for ValidateProduct.
type ValidateProductParams struct {
	Filehash string `form:"filehash" json:"filehash"`
}

// PutTracesV1JSONRequestBody defines body for PutTracesV1 for application/json ContentType.
type PutTracesV1JSONRequestBody = PutTracesV1JSONBody

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PingStatusGet request
	PingStatusGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutTracesV1 request with any body
	PutTracesV1WithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutTracesV1(ctx context.Context, body PutTracesV1JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchHashV1 request
	SearchHashV1(ctx context.Context, hash string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTraceV1 request
	GetTraceV1(ctx context.Context, productname string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ValidateProduct request
	ValidateProduct(ctx context.Context, productname string, params *ValidateProductParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PingStatusGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPingStatusGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutTracesV1WithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutTracesV1RequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutTracesV1(ctx context.Context, body PutTracesV1JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutTracesV1Request(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchHashV1(ctx context.Context, hash string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchHashV1Request(c.Server, hash)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTraceV1(ctx context.Context, productname string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTraceV1Request(c.Server, productname)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ValidateProduct(ctx context.Context, productname string, params *ValidateProductParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewValidateProductRequest(c.Server, productname, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPingStatusGetRequest generates requests for PingStatusGet
func NewPingStatusGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutTracesV1Request calls the generic PutTracesV1 builder with application/json body
func NewPutTracesV1Request(server string, body PutTracesV1JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutTracesV1RequestWithBody(server, "application/json", bodyReader)
}

// NewPutTracesV1RequestWithBody generates requests for PutTracesV1 with any type of body
func NewPutTracesV1RequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/traces")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSearchHashV1Request generates requests for SearchHashV1
func NewSearchHashV1Request(server string, hash string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hash", runtime.ParamLocationPath, hash)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/traces/hash/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTraceV1Request generates requests for GetTraceV1
func NewGetTraceV1Request(server string, productname string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "productname", runtime.ParamLocationPath, productname)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/traces/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewValidateProductRequest generates requests for ValidateProduct
func NewValidateProductRequest(server string, productname string, params *ValidateProductParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "productname", runtime.ParamLocationPath, productname)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/traces/%s/validate", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filehash", runtime.ParamLocationQuery, params.Filehash); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PingStatusGet request
	PingStatusGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PingStatusGetResponse, error)

	// PutTracesV1 request with any body
	PutTracesV1WithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutTracesV1Response, error)

	PutTracesV1WithResponse(ctx context.Context, body PutTracesV1JSONRequestBody, reqEditors ...RequestEditorFn) (*PutTracesV1Response, error)

	// SearchHashV1 request
	SearchHashV1WithResponse(ctx context.Context, hash string, reqEditors ...RequestEditorFn) (*SearchHashV1Response, error)

	// GetTraceV1 request
	GetTraceV1WithResponse(ctx context.Context, productname string, reqEditors ...RequestEditorFn) (*GetTraceV1Response, error)

	// ValidateProduct request
	ValidateProductWithResponse(ctx context.Context, productname string, params *ValidateProductParams, reqEditors ...RequestEditorFn) (*ValidateProductResponse, error)
}

type PingStatusGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *string
}

// Status returns HTTPResponse.Status
func (r PingStatusGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PingStatusGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutTracesV1Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *TraceRegistration
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r PutTracesV1Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutTracesV1Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchHashV1Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Trace
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r SearchHashV1Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchHashV1Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTraceV1Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Trace
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetTraceV1Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTraceV1Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ValidateProductResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TraceValidation
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ValidateProductResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ValidateProductResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PingStatusGetWithResponse request returning *PingStatusGetResponse
func (c *ClientWithResponses) PingStatusGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PingStatusGetResponse, error) {
	rsp, err := c.PingStatusGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePingStatusGetResponse(rsp)
}

// PutTracesV1WithBodyWithResponse request with arbitrary body returning *PutTracesV1Response
func (c *ClientWithResponses) PutTracesV1WithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutTracesV1Response, error) {
	rsp, err := c.PutTracesV1WithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutTracesV1Response(rsp)
}

func (c *ClientWithResponses) PutTracesV1WithResponse(ctx context.Context, body PutTracesV1JSONRequestBody, reqEditors ...RequestEditorFn) (*PutTracesV1Response, error) {
	rsp, err := c.PutTracesV1(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutTracesV1Response(rsp)
}

// SearchHashV1WithResponse request returning *SearchHashV1Response
func (c *ClientWithResponses) SearchHashV1WithResponse(ctx context.Context, hash string, reqEditors ...RequestEditorFn) (*SearchHashV1Response, error) {
	rsp, err := c.SearchHashV1(ctx, hash, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchHashV1Response(rsp)
}

// GetTraceV1WithResponse request returning *GetTraceV1Response
func (c *ClientWithResponses) GetTraceV1WithResponse(ctx context.Context, productname string, reqEditors ...RequestEditorFn) (*GetTraceV1Response, error) {
	rsp, err := c.GetTraceV1(ctx, productname, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTraceV1Response(rsp)
}

// ValidateProductWithResponse request returning *ValidateProductResponse
func (c *ClientWithResponses) ValidateProductWithResponse(ctx context.Context, productname string, params *ValidateProductParams, reqEditors ...RequestEditorFn) (*ValidateProductResponse, error) {
	rsp, err := c.ValidateProduct(ctx, productname, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseValidateProductResponse(rsp)
}

// ParsePingStatusGetResponse parses an HTTP response from a PingStatusGetWithResponse call
func ParsePingStatusGetResponse(rsp *http.Response) (*PingStatusGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PingStatusGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutTracesV1Response parses an HTTP response from a PutTracesV1WithResponse call
func ParsePutTracesV1Response(rsp *http.Response) (*PutTracesV1Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutTracesV1Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest TraceRegistration
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseSearchHashV1Response parses an HTTP response from a SearchHashV1WithResponse call
func ParseSearchHashV1Response(rsp *http.Response) (*SearchHashV1Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchHashV1Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Trace
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetTraceV1Response parses an HTTP response from a GetTraceV1WithResponse call
func ParseGetTraceV1Response(rsp *http.Response) (*GetTraceV1Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTraceV1Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Trace
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseValidateProductResponse parses an HTTP response from a ValidateProductWithResponse call
func ParseValidateProductResponse(rsp *http.Response) (*ValidateProductResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ValidateProductResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TraceValidation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xZ224cudF+FYL/D+wGaM1I3r0I5iqKrdgK1mtDUgwElmBwumumuWaTvSR7Jr3CvHtQ",
	"xT6wD/KMDwic3OyOm8ViHb6vWEU98tQUpdGgveOrR+7SHApBP58b7UF7/JmBS60svTSar/glK63JqtT/",
	"4FgahOj/QmrHfA6sFD5nQmf0j41UkAuX84SX1pRgvQTSTx9Xj9xLr4Cv+F0kzMyGNjfqFzzhvi5Rynkr",
	"9ZYfEo6njPfTyd7Ee1tVjc0zqg4Jt/B7JS1kfPU+6E2CeQ9Jp74NR7fdrH+D1KMlr+7u3r4TSmYCI3Rl",
	"rbFo2NDdDLyQCn9JDwV9+n8LG77i/7fsc7BsErAc6zv0lrwImjpDhLWiJjdaiTmDZuy+1mU1k18MpMSl",
	"NmascpBhWDOwcgdMdAsba4rFF2W21bDPZZoz6ZiFDVgL2Xyug/QHLQoYa8ZvY60jg+Ol1uQjIIgPnIIh",
	"RG4mpG/Dvk+QBn0F6XOwTFBUmPQO1CZhBr+kRilIcRP6hOtuGuAG2g2uNqJSnq/ePySnQatFcgSYu5i1",
	"barAjcLa891N0JfMZr3f2OVfOJYKlVZKeMjYuqYDtnIHmoV1tTVW+ryYBQLh8gv9DkkbeT0AupsCR7qn",
	"kNM5fiIoZ/1x8g/4dNBQgknNdFWswaLOde0DKBptUnvYgp1guMEuHTGFcIvUGRDfyq0WvrIwXxu8FSkw",
	"1wqxVGi2hi50O7ByU/dFwjEy0EpfL+71vUYV/WbpWGqBsFA5qbdMaCZcXYC3Mk1YWa2VTM8+Qs1Ap7Ym",
	"O5irnYdiEXRRONgacDPqhYylxoIrjc7au4BM/qFPZSaJYsLWCcZWmT3Ys1Q4SO41Ikeknv399s2vbGNs",
	"ITz7US5gwfbS56aimuXBlSJFhlimpIa1BfHR/Yn4Azo1GWSouPKbsz9P+dthfJz6Pi6dSBfXECZypxOb",
	"L5YUsw8foZ4gi1YYRrPBJmqiqFc+N5SieZRGgJi3t9E3DrQLtex4we2PSKLwDJyJwHsbSU/ge4c2zFXg",
	"ANzwdQ2OCeZKSOVGpgx22CpsqAS3tgsfSxgrt1JPc0k7Q1LVmw1fvf90ESLjrmjP4WFYioJ5pG/RFtQP",
	"T0IFVylzTwFFKBWXcqlDNaNTZrMcPByfQ9qMDQlu9ycMFtsFU178JXXpApxYyLg3mtzcpweorUvj6HRV",
	"2NimaejwhkVkCxoslpHFBLCnndtDanzyCOTRjSBcW3GaeyyY00KFrpoCnBdFiYaEYsJXPBMeznCJjxDQ",
	"SrN9DjrSmAuscKBjN09sYXhsRJfkpMHtBGVx7OI4EKeeItvV7olBIYJ0xLvc7CPfUlMQPL1hSm6A7ojn",
	"N1eXd1crdsk07OPOqff/Xj9/8/afKBItp6aUkNFNjUwQtF2ZlPrgxb1+cfXLVdAbbbJQmF27K5SA0I9Y",
	"EC7ULtBVgTENdvGE49k84UHfJFBXO5hnA63ewFY6b0WI0twNa8FVylP7JZoo2WjTtAgV4JzYDsrz6+bT",
	"XDmv0hSci6Vvm0+d9NoYBUJP63Qn2J45dn7g3lOI6aeTkyOw67d8z+6/i82cOH90TFQmHcyIQtdN8Rr7",
	"8Tjp/x6i3vaXBvQz/WrhtidGKnzoRclmdodfj1Uf9CMc1UhGcTo6mh6o09+YwV2EwRVrqaSv2S3YnUyB",
	"nbEXwgt2SUlpv/KE78C6AKbzxcXinG63ErQoJV/xnxbni2c8PCBQjJfOC1/Rzy1QHcOMkIHXGbbKUm9v",
	"SeQlIK1Dc+lCwp6dn0cjGaWsLJUM0V/+5gLCwy0T+3PTKGGonQX1LOgfR/aQjBjSwHVTKdaqoQS4qiiE",
	"rUN3v5MZOFYYLb1BRQwjihdQ24+JrcNMvTY6CPAH1LHcXSyJcOTdEw8EOMPqrDRS+6YygXVUbMPW0G1A",
	"36jf6+sNE7oe9ImOCWVBZDWDf0nnE1zRzcgEO2kq18rtpVI4Y5gd2L2V3gO5MEpT5Qkk7t0FD2AE5/9q",
	"svqz8nPSKBmuQ+SS1Ndhw8WoDkxH5CFFvK3gMMHSxWfZetTEQS2eAdK1zlA7OOZz4ePM7MECcx3OVN3l",
	"OUw2UXYxDj+f/zSDk6AK50OjVY0JjJSs63bq+IOGP7AuqLqYU2UMKxA/sXlSp6rKenualActz559s1DO",
	"PafNBLMXYa1MTMmbjiehLXEQ3ibnCBPR87KP0T8wRmOWLrGBWz7ifw9RBfs0Y31ltaMJoTk+bnvaoaGb",
	"1ru3m0JQEodPQmYfXm7oAUv6Vohu7unD0ZS2tyBsmr8SLifelsKKAjBOdOvhQNI+yYaHFt68Jg+plMyU",
	"2FdBcFxOH76ygn9ehZjU++AvQ+MYeTytErM0whT1b2VdTogJG1PprCHiz9P0/2riPJ+g5Dskz2mQjYhD",
	"YWM34K2EnVAT3jw24ERUfSPmtEMFqiT2vK6Ul6VqRx2kBl11zS4n9Vb1o603TDYFecSxXDpvbH2vf6S5",
	"m2ZyaXSCA08t9TZhGSjAT+EJqn+sGHLtJYQr8kSmRRE6iXBvB/LfGe9egmcBE1/Ouu6vFl9Buqd0/Ldx",
	"bgD2L+Xdspnq4EQCtuJuYobYCqmdD5cO9r7ZoCoMedB4Dv0j+H+aDElzxu8V2Lo/JPpr6fET/tYLf2uu",
	"HaVYNOZ+xZVFxUpEo33/0lWCxXEF/pcZ9u4ENB+74KJEPBwOh8O/AwAA//+h6mWM0h8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
